"""added timestamps

Revision ID: 547fccea573e
Revises: 
Create Date: 2026-05-15 13:17:11.780207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547fccea573e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagination', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('pagination', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'pagination', ['host_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pagination', type_='unique')
    op.drop_column('pagination', 'updated_at')
    op.drop_column('pagination', 'created_at')
    # ### end Alembic commands ###
